### ISSUE TITLE
Баг отображения постов

### ISSUE THREAD

**Issue by surious-type** [GreyRuler/app-android#14]
**Шаги для воспроизведения**

1. Запускаем проект
2. Создаём пост (1) (если нет никаких).
3. Нажимаем на него.
4. Возвращаемся обратно.
5. Пробуем создать ещё один пост (2).
6. И мы видим, что пост не отобразился.
7. Но, если повторить шаги 3-4, созданный пост (2) появится.

**Ожидаемый результат:**

Корректное отображение постов

**Окружение:**

ОС Windows 10 64
Версия Kotlin: 212-1.6.21-release-334-AS5457.46
Ссылка на исходники проекта на GitHub: https://github.com/GreyRuler/app-android/tree/feature/Fragments

**Comment by GreyRuler** [comment]
Fixed
